export {default as PlusIcon} from './plus.svg';
export {default as BackIcon} from './back.svg';
export {default as CityIcon} from './city.svg';
export {default as ProfileIcon} from './profile.svg';
export {default as ProfileWhiteIcon} from './profileWhite.svg';
export {default as QrCodeIcon} from './qr-code.svg';
export {default as ClockIcon} from './clock.svg';
export {default as PaymentIcon} from './payment.svg';
export {default as PhoneIcon} from './phone.svg';
export {default as SettingsIcon} from './settings.svg';
export {default as MastercardIcon} from './mastercard.svg';
export {default as CheckIcon} from './check.svg';
export {default as MoreIcon} from './more.svg';
export {default as FlagUAIcon} from './ua-flag.svg';
export {default as CheckboxIcon} from './checbox.svg';
export {default as CheckboxCheckedIcon} from './checkbox-checked.svg';
export {default as CloseIcon} from './close.svg';
export {default as ClockBlackIcon} from './clock-black.svg';
export {default as PowerbankIcon} from './power-bank.svg';
export {default as LocationIcon} from './location.svg';
export {default as SuccessIcon} from './success.svg';

// export {default as SmallArrowDown} from './small_arrow_down.svg';
